### ISSUE TITLE
Unable to find functions / modules

### ISSUE THREAD

**Issue by gbarz** [robertdj/SparseGrids.jl#1]
Something seems buggy with the internal package management "using" and "include" (at least on my El Capitan Mac with Julia 0.4.6)

SparseGrids does not seem to locate the  "kpn"  function when called. For example:  
sparsegrid(3,5,f=kpn).  However, when kpn is copied explicitly from your source code and defined in the Julia kernel, the example works.

Additionally, SparseGrids does not recognize gausshermite unless an explicit statement  "using FastGuassQuadrature" is run in advance of "using SparseGrids".

**Comment by robertdj** [comment]
That sounds like a mess. I haven't used this package in a while, so thanks for pointing that out!

I'm very busy this week, but I will look into fixing the issues next week.

**Comment by robertdj** [comment]
Next week turned into next next week, but now it should be working now. Note, however, that you need a small change in the syntax:

    sparsegrid(3, 5, kpn)

I.e., don't use `f=kpn`.

I don't have any problems with `FastGuassQuadrature`, although I get 'deprecated' warnings. I've tested on Julia 0.4.5 on Linux and on Linux and Mac with Travis. 

The changes are **not** official yet, so get the test version by 

    Pkg.update()
    Pkg.checkout("SparseGrids")

Let me know if it works for you.

**Comment by gbarz** [comment]
Thank you.  Appreciate your help. It is working seamlessly now.  

SparseGrids is very helpful for me.

**Comment by robertdj** [comment]
I'm glad it's working for you! I'll soon submit a registration for a new tag.
